name: TFC Workflows

on:
  push:
    branches:
      - prod
    paths: ["terraform/*"]

permissions: write-all

jobs:
  deploy:
    env:
      TF_CLOUD_ORGANIZATION: ${{ github.repository_owner }}
      TF_API_TOKEN: ${{ secrets.TFE_TOKEN }}
    name: "Build and Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Check state of initial-deploy workflow
        id: check_state
        run: |
          echo "initial_deploy_state=$(gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/workflows/initial-deploy.yml | jq -r '.state')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Checkout
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Get next version
        uses: reecetech/version-increment@a29aa752dc3b8118a2dc2ed93faf0e95a73a9c7e
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        id: version
        with:
          scheme: calver
          increment: patch

      - name: Create release
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        env:
          VERSION: ${{ steps.version.outputs.version }}
        with:
          github-token: "${{ github.token }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.VERSION,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.VERSION,
                target_commitish: 'prod'
              });
              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }

      - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@8e08d1ba957673f5fbf971a22b3219639dc45661
        id: upload
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        with:
          workspace: ${{ github.event.repository.name }}
          directory: terraform

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@8e08d1ba957673f5fbf971a22b3219639dc45661
        id: apply-run
        if: ${{ steps.check_state.outputs.initial_deploy_state == 'disabled_manually' }}
        with:
          workspace: ${{ github.event.repository.name }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          plan_only: false
